name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: joeltorcato
          outputs: dist/github-contribution-grid-snake.svg

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/"